// Runs the production offline HTML in Node's VM with a recording Canvas2D/DOM adapter.
// Uses only Node built-ins. This checks transforms and control logic; it does not render pixels
// or claim a successful browser/native-Spine visual check. Run: node validation/check_viewer.cjs
const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const path=require('path'),base=path.resolve(__dirname,'..'),html=fs.readFileSync(base+'/preview/index.html','utf8'),source=JSON.parse(fs.readFileSync(base+'/source/hao.spine-json','utf8')),rig=JSON.parse(fs.readFileSync(base+'/editable/rig.json','utf8'));
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),block=id=>html.match(new RegExp('<script type="application/json" id="'+id+'">([\\s\\S]*?)</script>'))[1],meta=JSON.parse(block('source-meta'));
for(const [key,path]of [['spine','source/hao.spine-json'],['png','source/hao.png'],['rig','editable/rig.json']])assert.equal(meta[key],sha(base+'/'+path));
assert.deepStrictEqual(JSON.parse(block('spine-data')),source);assert.deepStrictEqual(JSON.parse(block('region-data')),rig.regions);assert.ok(!/<script\b[^>]*\bsrc\s*=/.test(html));assert.ok(!/@import/.test(html));
const multiply=(p,m)=>[p[0]*m[0]+p[2]*m[1],p[1]*m[0]+p[3]*m[1],p[0]*m[2]+p[2]*m[3],p[1]*m[2]+p[3]*m[3],p[0]*m[4]+p[2]*m[5]+p[4],p[1]*m[4]+p[3]*m[5]+p[5]];
const ctx={matrix:[1,0,0,1,0,0],stack:[],records:[],globalAlpha:1,globalCompositeOperation:'source-over',save(){this.stack.push({m:this.matrix.slice(),a:this.globalAlpha,b:this.globalCompositeOperation});},restore(){const s=this.stack.pop();this.matrix=s.m;this.globalAlpha=s.a;this.globalCompositeOperation=s.b;},setTransform(...m){this.matrix=m;},transform(...m){this.matrix=multiply(this.matrix,m);},translate(x,y){this.transform(1,0,0,1,x,y);},scale(x,y){this.transform(x,0,0,y,0,0);},rotate(r){this.transform(Math.cos(r),Math.sin(r),-Math.sin(r),Math.cos(r),0,0);},drawImage(...args){this.records.push({m:this.matrix.slice(),alpha:this.globalAlpha,blend:this.globalCompositeOperation,rect:args.slice(1)});}};
for(const name of ['clearRect','beginPath','ellipse','fill','moveTo','lineTo','closePath','clip','stroke','arc'])ctx[name]=()=>{};
class Element{constructor(id){this.id=id;this.listeners={};this.attributes={};this.style={};this.value='';this.checked=false;this.hidden=id==='error';this.classList={classes:new Set(),toggle(n,on){if(on)this.classes.add(n);else this.classes.delete(n);}};}addEventListener(n,fn){this.listeners[n]=fn;}setAttribute(k,v){this.attributes[k]=v;}click(){this.listeners.click?.({target:this});}dispatch(n){this.listeners[n]?.({target:this});}}
const elements={},el=id=>elements[id]??(elements[id]=new Element(id));for(const id of ['spine-data','region-data','source-meta'])el(id).textContent=block(id);
el('canvas').width=1100;el('canvas').height=800;el('canvas').getContext=()=>ctx;el('loop').checked=true;el('speed').value='1';
const buttons=['attack','cast'].map(name=>{const e=new Element(name);e.dataset={animation:name};return e;});let loadedHash=null,raf=null,clock=1;
class Image{set src(url){assert.ok(url.startsWith('data:image/png;base64,'));const bytes=Buffer.from(url.split(',')[1],'base64');loadedHash=crypto.createHash('sha256').update(bytes).digest('hex');this.width=bytes.readUInt32BE(16);this.height=bytes.readUInt32BE(20);this.onload();}}
const sandbox={console,Image,performance:{now:()=>clock},document:{getElementById:el,querySelectorAll:()=>buttons,addEventListener(){}},requestAnimationFrame(fn){raf=fn;}};sandbox.window=sandbox;sandbox.devicePixelRatio=1;sandbox.addEventListener=()=>{};
vm.createContext(sandbox);vm.runInContext(html.split('<script>')[1].split('</script>')[0],sandbox,{timeout:20000});const api=sandbox.haoViewer;assert.ok(api.getState().ready,JSON.stringify(api.getState()));assert.equal(api.getState().error,null);assert.equal(loadedHash,meta.png);
const sample=(f,t,k,d)=>{if(!f?.length||t<(f[0].time||0))return d;for(let i=0;i<f.length-1;i++){const a=f[i],b=f[i+1];if(t<(b.time||0)){if(a.curve==='stepped')return a[k]??d;const q=(t-(a.time||0))/((b.time||0)-(a.time||0));return (a[k]??d)*(1-q)+(b[k]??d)*q;}}return f.at(-1)[k]??d;};
function pose(name,t){const world={};for(const b of source.bones){const f=source.animations[name].bones[b.name]||{},r=(b.rotation||0)+sample(f.rotate,t,'value',0),sx=(b.scaleX??1)*sample(f.scale,t,'x',1),sy=(b.scaleY??1)*sample(f.scale,t,'y',1),rx=(r+(b.shearX||0)+sample(f.shear,t,'x',0))*Math.PI/180,ry=(r+90+(b.shearY||0)+sample(f.shear,t,'y',0))*Math.PI/180,m=[Math.cos(rx)*sx,Math.sin(rx)*sx,Math.cos(ry)*sy,Math.sin(ry)*sy,(b.x||0)+sample(f.translate,t,'x',0),(b.y||0)+sample(f.translate,t,'y',0)];world[b.name]=b.parent?multiply(world[b.parent],m):m;}return world;}
const mesh=source.skins[0].attachments.cape.cape;
assert.equal(source.bones.length,22);assert.equal(source.slots.length,20);assert.equal(mesh.uvs.length/2,77);assert.equal(mesh.triangles.length/3,120);
function meshWorld(world){let i=0;const points=[];for(let v=0;v<mesh.uvs.length/2;v++){let x=0,y=0;const n=mesh.vertices[i++];for(let b=0;b<n;b++){const index=mesh.vertices[i++],lx=mesh.vertices[i++],ly=mesh.vertices[i++],w=mesh.vertices[i++],m=world[source.bones[index].name];x+=(m[0]*lx+m[2]*ly+m[4])*w;y+=(m[1]*lx+m[3]*ly+m[5])*w;}points.push([x,y]);}assert.equal(i,mesh.vertices.length);return points;}
const apply=(m,x,y)=>[m[0]*x+m[2]*y+m[4],m[1]*x+m[3]*y+m[5]],cape=rig.regions.cape,ox=meta.origin[0],oy=meta.origin[1],scale=meta.scale;
let maxBone=0,maxMesh=0,maxUV=0,maxRegion=0,boneChecks=0,poseChecks=0;
for(const [name,times]of Object.entries({attack:[0,.233333,.366667,.4,.67,1],cast:[0,.57,.8,1.4]}))for(const t of times){poseChecks++;const expected=pose(name,t),observed=api.poseAt(name,t),want=meshWorld(expected),got=api.meshVertices(name,t,'cape');for(const b of source.bones)for(const [i,k]of ['a','b','c','d','x','y'].entries()){const e=Math.abs(expected[b.name][i]-observed.world[b.name][k]);maxBone=Math.max(maxBone,e);assert.ok(e<1e-7);boneChecks++;}for(let i=0;i<77;i++)for(let k=0;k<2;k++){const e=Math.abs(want[i][k]-got[i][k]);maxMesh=Math.max(maxMesh,e);assert.ok(e<1e-7);}
ctx.records=[];api.renderFrame(name,t);const draws=ctx.records.filter(r=>r.rect[0]===cape.x&&r.rect[1]===cape.y);assert.equal(draws.length,120);for(let tri=0;tri<120;tri++)for(let c=0;c<3;c++){const i=mesh.triangles[tri*3+c],p=apply(draws[tri].m,mesh.uvs[i*2]*cape.width,mesh.uvs[i*2+1]*cape.height),target=[ox+want[i][0]*scale,oy-want[i][1]*scale];for(let k=0;k<2;k++){const e=Math.abs(p[k]-target[k]);maxUV=Math.max(maxUV,e);assert.ok(e<1e-6);}}
for(const part of ['torso','weapon']){const att=source.skins[0].attachments[part][part],r=rig.regions[att.path],draw=ctx.records.find(d=>d.rect[0]===r.x&&d.rect[1]===r.y),bone=expected[source.slots.find(s=>s.name===part).bone],angle=(att.rotation||0)*Math.PI/180;for(const [dx,dy]of [[-att.width/2,-att.height/2],[att.width/2,-att.height/2],[att.width/2,att.height/2],[-att.width/2,att.height/2]]){const x=(att.x||0)+Math.cos(angle)*dx*(att.scaleX??1)+Math.sin(angle)*dy*(att.scaleY??1),y=(att.y||0)+Math.sin(angle)*dx*(att.scaleX??1)-Math.cos(angle)*dy*(att.scaleY??1),q=apply(bone,x,y),target=[ox+q[0]*scale,oy-q[1]*scale],p=apply(draw.m,dx,dy);for(let k=0;k<2;k++){const e=Math.abs(p[k]-target[k]);maxRegion=Math.max(maxRegion,e);assert.ok(e<1e-7);}}}}
const alpha=(n,t,s)=>api.poseAt(n,t).slots.find(x=>x.name===s).alpha;assert.equal(alpha('attack',0,'fx_slash'),0);assert.equal(alpha('attack',.4,'fx_slash'),.65);assert.equal(alpha('cast',.8,'fx_aura'),1);assert.equal(alpha('cast',1.4,'fx_aura'),0);ctx.records=[];api.renderFrame('attack',.4);const slash=rig.regions.fx_slash;assert.ok(ctx.records.some(r=>r.rect[0]===slash.x&&r.rect[1]===slash.y&&r.alpha===.65&&r.blend==='lighter'));
buttons[1].click();assert.equal(api.getState().animation,'cast');el('event-jump').click();assert.equal(api.getState().time,.8);el('bones').checked=true;el('bones').dispatch('change');assert.ok(api.getState().showBones);el('backdrop').checked=true;el('backdrop').dispatch('change');assert.ok(el('stage').classList.classes.has('checker'));el('speed').value='.5';assert.equal(api.getState().speed,.5);el('loop').checked=false;api.renderFrame('cast',1.35);el('play').click();clock+=100;raf(clock);assert.equal(api.getState().playing,false);assert.equal(api.getState().time,1.4);buttons[0].click();el('scrub').value='.37';el('scrub').dispatch('input');assert.equal(api.getState().time,.37);assert.equal(api.getState().playing,false);
const setup=meshWorld(pose('attack',0)),bounds=[Math.min(...setup.map(p=>p[0])),Math.min(...setup.map(p=>p[1])),Math.max(...setup.map(p=>p[0])),Math.max(...setup.map(p=>p[1]))];
const report={status:'PASS',method:'Production HTML executed in Node VM with recording Canvas2D/DOM adapter, not browser visual verification',sourceHashes:{spine:meta.spine,rig:meta.rig,png:meta.png},htmlSha256:sha(base+'/preview/index.html'),canvas:meta.canvas,origin:meta.origin,scale,bones:source.bones.length,posesChecked:poseChecks,boneComponentChecks:boneChecks,meshVertices:77,meshTriangles:120,maxBoneError:maxBone,maxMeshError:maxMesh,maxUVError:maxUV,maxRegionError:maxRegion,setupMeshBounds:bounds,fxAlpha:{attackHit:.65,castRelease:1},ui:['attack/cast','event-jump','bones','checker','speed','loop-end','scrub'],externalDependencies:false,browserVisualCheck:{status:'unverified',reason:'Optional headless Edge launch failed before a page opened: Crashpad TransactNamedPipe failure. No retry was performed.'},testScope:'Numerical and logic checks from actual production HTML. Recording Canvas2D adapter verifies affine draw calls; it does not rasterize the atlas.'};
const windup=api.poseAt('attack',8/30).world,hit=api.poseAt('attack',12/30).world;
const direction={coordinates:'Spine Y-up',windupTime:8/30,hitTime:12/30,wristDelta:[hit.hand_main.x-windup.hand_main.x,hit.hand_main.y-windup.hand_main.y],gripDelta:[hit.weapon.x-windup.weapon.x,hit.weapon.y-windup.weapon.y],bladeAngleDelta:Math.atan2(hit.weapon.b,hit.weapon.a)-Math.atan2(windup.weapon.b,windup.weapon.a)};
assert.ok(direction.wristDelta[0]>0&&direction.wristDelta[1]<0,'Striking wrist must travel forward and down with the sword.');
assert.ok(direction.gripDelta[0]>0&&direction.gripDelta[1]<0,'Sword grip must follow the forward/down hand path.');
assert.ok(direction.bladeAngleDelta<0,'Blade must descend during the strike.');
report.attackDirection=direction;
fs.writeFileSync(path.join(__dirname,'viewer-check.json'),JSON.stringify(report,null,2)+'\n','utf8');
console.log(JSON.stringify(report));
